spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: app_user
    password: app_password_123
    virtual-host: /app
    connection-timeout: 60000
  datasource:
    url: jdbc:mysql://localhost:3306/apisystem?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      encoding: UTF-8
  mail:
    host: ${MAIL_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAIL_PORT:2525}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 4MB
pag:
  url: http://localhost:8081

infobip:
  base:
    url: ${INFOBIP_BASE_URL:https://xk4qx3.api.infobip.com}
  api:
    key: a
  whatsapp:
    sender: a
    template:
      name: a

discord:
  webhook:
    url: a

storage:
  local-dir: imagens
logging:
  level:
    org.springframework.amqp: DEBUG

