server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_api_system
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: senhaSeguraAqui

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: a4bf5efe97da28
    password: 5b58865b16d7db
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  swagger-ui:
    enabled: true

storage:
  local-dir: imagens
