# yaml
server:
  port: ${SERVER_PORT:8080}

spring:
  servlet:
    multipart:
      max-file-size: ${MULTIPART_MAX_FILE_SIZE:10MB}
      max-request-size: ${MULTIPART_MAX_REQUEST_SIZE:10MB}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/spring_api_system?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:Sa123@}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:false}

  mail:
    host: ${MAIL_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAIL_PORT:2525}
    username: ${MAIL_USERNAME:ci}
    password: ${MAIL_PASSWORD:ci}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS_ENABLE:false}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:/}
    connection-timeout: ${RABBITMQ_CONNECTION_TIMEOUT:60000}

  cache:
    type: redis
  data:
    redis:
      url: ${SPRING_REDIS_URL:redis://localhost:6379}

pag:
  url: ${PAG_API_URL:http://localhost:8081}

infobip:
  base:
    url: ${INFOBIP_BASE_URL:}
  api:
    key: ${INFOBIP_API_KEY:}
  whatsapp:
    sender: ${INFOBIP_WHATSAPP_SENDER:}
    template:
      name: ${INFOBIP_TEMPLATE_NAME:authentication}

discord:
  webhook:
    url: ${DISCORD_WEBHOOK_URL:}

springdoc:
  swagger-ui:
    enabled: ${SPRINGDOC_SWAGGER_UI_ENABLED:false}

storage:
  type: ${STORAGE_TYPE:local}
  s3:
    bucket: ${AWS_S3_BUCKET:}
    path: ${STORAGE_S3_PATH:}

aws:
  region: ${AWS_REGION:}
  s3:
    bucket: ${AWS_S3_BUCKET:}
    endpoint: ${AWS_S3_ENDPOINT:}
    path-style-access: ${AWS_S3_PATH_STYLE:false}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.spring: ${LOGGING_LEVEL_COM_SPRING:INFO}

init:
  email: ${INIT_EMAIL:admin@example.com}
  password: ${INIT_PASSWORD:changeit}
