spring:
  ai:
    google:
      genai:
        api-key: ${GOOGLE_API_KEY:a}
        chat:
          options:
            model: ${GOOGLE_GEMINI_MODEL:gemini-2.5-flash}
  application:
    name: spring-api-system
  web:
    resources:
      add-mappings: false
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
    add-properties: false
  profiles:
    default: prod
    active: dev
  config:
    import: "optional:classpath:application-${spring.profiles.active}.yml"


jwt:
  public:
    key: classpath:keys/public.pem
  private:
    key: classpath:keys/private.pem

springdoc:
  swagger-ui:
    path: /doc

argon:
  algoritmo: argon2id
  versao: 19
  saltLength: 32
  hashLength: 32
  parallelism: 1
  memory: 65536
  iterations: 3

logging:
  level:
    org.example: INFO
    org.springframework.data.redis: DEBUG
    org.springframework.cache: TRACE

app:
  mock:
    seed:
      enabled: false
