spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:app_user}
    password: ${RABBITMQ_PASSWORD:app_password_123}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:/app}
    connection-timeout: 60000
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
      encoding: UTF-8
  mail:
    host: ${MAIL_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAIL_PORT:2525}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

pag:
  url: ${PAG_URL:http://localhost:8081}

messaging:
  rabbitmq:
    enabled: ${MESSAGING_RABBITMQ_ENABLED:false}

infobip:
  base:
    url: ${INFOBIP_BASE_URL:https://xk4qx3.api.infobip.com}
  api:
    key: ${INFOBIP_API_KEY:a}
  whatsapp:
    sender: ${INFOBIP_WHATSAPP_SENDER:a}
    template:
      name: ${INFOBIP_WHATSAPP_TEMPLATE_NAME:a}

discord:
  webhook:
    url: ${DISCORD_WEBHOOK_URL:a}

storage:
  local-dir: ${STORAGE_LOCAL_DIR:imagens}
logging:
  level:
    org.springframework.amqp: DEBUG
