package com.spring.ApiSystem.agendamento.enums;

public enum AgendamentoStatus {
    APROVADO,
    PENDENTE_CLIENTE_APROVACAO,
    PENDENTE_PERSONAL_APROVACAO,
    CONCLUIDO,
    PENDENTE_PERSONAL_CONCLUIR,
    CANCELADO_CLIENTE,
    CANCELADO_PERSONAL,
    AUSENCIA_CLIENTE,
    AUSENCIA_PERSONAL,
}
